# Basic Python Syntax

**Learning Objective:** Identify and use the basic syntax of the Python language including variables, functions, objects and packages.

This notebook is meant to provide the absolute minimal syntax needed to start using Python packages such as NumPy, SciPy, Matplotlib, etc. for data science. For a full tutorial to the Python language see [codecademy's](http://www.codecademy.com/) excellent [Python Course](http://www.codecademy.com/tracks/python).

## Objects

* Objects are the **nouns** of the Python programming language.
* Objects are the virtual equivalent of "people, places and things."
* Objects typically encode some sort of **data**.
* In Python, everything is an object.

Here are some examples of objects.

An `str`, or string, is a bit of text:

In [1]:
"Hi there"

'Hi there'

An `int`, or integer, is a number without a decimal point:

In [2]:
12345

12345

A `float`, or floating point number, is a number with a decimal point:

In [3]:
3.141

3.141

A `bool` or boolean, is a value that can either be true or false:

In [4]:
True

True

In [5]:
False

False

Some objects are containers. That is, they *contain* other objects. Here is a `list`, which is an ordered sequence objects:

In [6]:
b = [0,1,2,3,4,5]

In [7]:
b[0] = 2

In [8]:
b

[2, 1, 2, 3, 4, 5]

In [9]:
a = (0,1,2,3,4)

In [10]:
a[0] = 1

TypeError: 'tuple' object does not support item assignment

Here is a `dict`, or dictionary. A `dict` is an unordered pair of `{'key': value}` pairs:

In [ ]:
{'name': 'Bart Simpson',
 'address': '742 Evergreen Terrace'}

You can return type of an object using the `type` function:

In [ ]:
type(b)

## Variables

* A variable is a way of naming or labeling an object.
* A variable is created using a single `=` sign.
* In Python, variables should have names with lowercase characters and underscores between words. 

Create a variable named `a` with the value `Hi There`:

In [ ]:
a = 'Hi There'

Notice that there is no output when a variable is created. To see the value of a variable, you can use the `print` function:

In [ ]:
print(a)

Create a variable named `b` with the value `12345`:

In [ ]:
b = 12345

Create a variable named `c` with the value `3.141`:

In [ ]:
c = 3.141

Create variables `c` and `d` pointing to a list and a dict:

In [ ]:
d = [0,1,2,3,4,5]

In [ ]:
e = {'name': 'Bart Simpson',
     'address': '742 Evergreen Terrace'}

## Functions

* If objects are the **nouns** of Python syntax, then functions are the **verbs**.
* Functions perform actions on objects.
* In Python, functions are defined using `def` and called with parentheses `()`.
* In Python, variables should have names with lowercase characters and underscores between words. 

Let's define a simple function `f` that returns the sum of its arguments `x` and `y`:

In [ ]:
def f(x,y):
    return x+y

We "call" the function with the exact same notation we would use in mathematics:

In [ ]:
f(2,2)

In [ ]:
f(1.0, 2.0)

In [ ]:
f('hi','there')

Another way of calling a function is by explicitely naming the arguments:

In [ ]:
f(x=2,y=2)

Here the arguments are passed as **keywords**.

If you don't know how a function works, you can use `?` to get help:

In [ ]:
import math

In [12]:
math.cos?

Object `math.cos` not found.


## Object containment

* Objects can contain other objects.
* In Python, custom objects are declared using `class` and instantiated by the `()` call syntax.
* In Python, object containment is indicated using the `parent.child` syntax.
* In Python, custom objects should have names with `UppercaseLetters` starting each word.

Here is declare a `Student` class:

In [13]:
class Student():
    pass

Create an instance of a student by calling the `Student` class:

In [14]:
bart = Student()

A student has a `name` and `address` that are accessed using a `.`:

In [15]:
bart.name = "Bart Simpson"
bart.address = "742 Evergreen Terrace"

In [16]:
bart.name

'Bart Simpson'

In [17]:
bart.address

'742 Evergreen Terrace'

Notice how the objects contained inside a `Student` themselves have names (they are variables). Variables that are attached to objects are called **attributes**.

You can use "tab completion" to inspect what attributes an object has:

In [18]:
bart.

SyntaxError: invalid syntax (<ipython-input-18-20183839840a>, line 1)

## Functions attached to objects

* Objects can have functions attached to them, which are **verbs** that act on the **nouns**.
* For example we might want to *start* a *car*.
* In Python, functions attached to objects are called **methods**.
* A method involves **containment** and a **verb** so you need to use both `.` and `()`.

Here is a Python list:

In [19]:
colors = ['blue', 'red', 'green']

The list object can be sorted using the `sort` method:

In [20]:
colors.sort()

In [21]:
colors

['blue', 'green', 'red']

## Resources

* The full [Python Documentation](https://docs.python.org/2/).
* The [Python Style Guide](http://legacy.python.org/dev/peps/pep-0008/), or "PEP8," describes the recommended conventions for writing Python code.